### ISSUE TITLE
Add EnvelopedData or AuthEnvelopedData messages containing the new KEMRecipientInfo structure

### ISSUE THREAD

**Issue by codespree** [codespree/quantcrypt#1]
Support for KEM / DSA certificates is now complete:
```
 use quantcrypt::CertificateBuilder;
 use quantcrypt::DsaAlgorithm;
 use quantcrypt::KemAlgorithm;
 use quantcrypt::Profile;
 use quantcrypt::DsaKeyGenerator;
 use quantcrypt::KemKeyGenerator;

 // Create a TA key pair
 let (pk_root, sk_root) = DsaKeyGenerator::new(DsaAlgorithm::MlDsa44).generate().unwrap();
 let serial_no: [u8;20] = [0; 20];

 // Create the TA certificate
 let cert_root = CertificateBuilder::new(Profile::Root)
    .set_serial_number(&serial_no)
    .set_not_after("2025-01-01T00:00:00Z")
    .set_subject("CN=example.com")
    .set_public_key(pk_root.clone())
    .build(&sk_root).unwrap();
 assert!(cert_root.verify_self_signed().unwrap());

 // Create a leaf key pair for KEM
 let (pk_kem, sk_kem) = KemKeyGenerator::new(KemAlgorithm::MlKem512).generate().unwrap();
 let cert_kem = CertificateBuilder::new(Profile::Leaf {
   issuer: "CN=example.com".parse().unwrap(),
   enable_key_agreement: false,
   enable_key_encipherment: true,
 })
   .set_serial_number(&serial_no)
   .set_not_after("2025-01-01T00:00:00Z")
   .set_subject("CN=ssai.example.com")
   .set_public_key(pk_kem)
   .set_signers_public_key(pk_root)
   .build(&sk_root).unwrap();

 // It's not self signed so verification as self signed should fail
 assert!(!cert_kem.verify_self_signed().unwrap());

 // But it should verify against the root
 assert!(cert_root.verify_child(&cert_kem).unwrap());
```

@carl-wallace do you think we should join hands and make this more robust, tested, and in library form.

**Comment by carl-wallace** [comment]
The encoder/decoder I worked on is in the cms crate here: https://github.com/RustCrypto/formats/tree/master/cms/src. Releasing a builder implementation there probably makes sense. I've been in a holding pattern waiting for a FIPS-aligned implementations to be published. I used [pqcrypto](https://crates.io/crates/pqcrypto) before, but they've not yet updated (see issues [here](https://github.com/rustpq/pqcrypto/issues)). There is an SLH-DSA implementation in [RustCrypto/signatures](https://github.com/RustCrypto/signatures/), but no ML-DSA yet. They do have [ML-KEM](https://github.com/RustCrypto/KEMs/tree/master/ml-kem) but I've not integrated it yet.

**Comment by codespree** [comment]
@carl-wallace, I have included some code from kemri toy in this repository, thanks for your help. It will help in closing this issue soon.

However, I have questions with respect to `AuthenticatedEnvelopedData`. The [RFC](https://datatracker.ietf.org/doc/html/rfc5652#section-11.1) states that `Content Type` and `Message Digest` attributes should be included as authenticated attributes. Your implementation did not include these.

Do you think they should be included?

**Comment by carl-wallace** [comment]
This code was really just focused on the KEM elements. It would need to include requires attributes as you note (as does the SignedDataBuilder).

**Comment by codespree** [comment]
@carl-wallace I discovered my source of confusion. I was mistaking `AuthEnvelopedData` in RFC 5083 with `AuthenticatedData` defined in RFC5652. 

RFC 5083 says:
```
         authAttrs optionally contains the authenticated attributes.  The
         CMS authenticated-data content type uses the same type to carry
         authenticated attributes.  The authAttrs MUST be present if the
         content type carried in EncryptedContentInfo is not id-data.
         AuthAttributes MUST be DER encoded, even if the rest of the
         AuthEnvelopedData structure is BER encoded.  The AuthAttributes
         type is defined in Section 9.1 of [[CMS](https://datatracker.ietf.org/doc/html/rfc5083#ref-CMS)]; however, in this case,
         the message-digest attribute **SHOULD NOT be included**.  Useful
         attribute types are defined in Section 11 of [[CMS](https://datatracker.ietf.org/doc/html/rfc5083#ref-CMS)].
```

`AuthenticatedData` is defined in [RFC5652](https://datatracker.ietf.org/doc/html/rfc5652#section-11.2) and RFC5652 states:
```
   The message-digest attribute type specifies the message digest of the
   encapContentInfo eContent OCTET STRING being signed in signed-data
   (see Section 5.4) or authenticated in authenticated-data (see Section
   9.2).  For signed-data, the message digest is computed using the
   signer's message digest algorithm.  For authenticated-data, the
   message digest is computed using the originator's message digest
   algorithm.
```

In RFC9629 ML-KEM refers to `AuthEnvelopedData` from RFC5083. `AuthEnvelopedData`, however, should **NOT** have the message digest attribute.

So, your implementation was perfectly correct from my understanding. Also, content type is only mandatory when content type is not id-data.
